### ISSUE TITLE
coot-1 build fail 

### ISSUE THREAD

**Issue by jelka71** [pemsley/coot#40]
Running the build-it-3-3 script to compile coot-1, this error occurs: 

> 
>                  from ../../coot/src/init_coot_as_python_module.cc:12:
> ../../coot/src/Mesh.hh:10:10: fatal error: g_triangle.hh: No such file or directory
>  #include "g_triangle.hh"
>           ^~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:2067: recipe for target 'init_coot_as_python_module.lo' failed
> make[1]: *** [init_coot_as_python_module.lo] Error 1
> make[1]: Leaving directory '/scratch/download/coot/build-coot/src'
> Makefile:723: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
> make failed. 

g_triangle.hh does not seem to be in the source code?

**Comment by pemsley** [comment]
That's right - it's a mistake - it's not in the tar file - but is in the git repo. I fixed this in 8a550246932a864c9e893ec87eae6ba00787e637.

**Comment by jelka71** [comment]
Thanks Poul, 
Although it does not seem to be in the master, but the missing file seems to be in the gtk3 branch. 
Is this the branch that should be used?

**Comment by pemsley** [comment]
>  Is this the branch that should be used?
Yes, for the moment Coot 1 development is going on in the gtk3 branch.

**Comment by jelka71** [comment]
Okay Thanks, 
I finally got this to build on Ubuntu 18.04, but I had to change "_scm_listify_" to "_scm_list_n_" in "_coot_wrap_guile.cc_" and  "_coot_wrap_guile_pre.cc_" to make it complete build. Bug?

**Comment by jcbollinger** [comment]
I saw the same issue:
```
In file included from /usr/include/guile/2.2/libguile.h:128,
                 from coot_wrap_guile.cc:754:
coot_wrap_guile.cc: In function 'scm_unused_struct* _wrap_vector_string_popN___(SCM)':
/usr/include/guile/2.2/libguile/deprecated.h:115:21: error: 'scm_listify__GONE__REPLACE_WITH__scm_list_n' was not declared in this scope
 #define scm_listify scm_listify__GONE__REPLACE_WITH__scm_list_n
```
This happens when I compile against guile 2.2, which is what the build-it script seems to want, but not if I compile against guile 2.0.

**Comment by jcbollinger** [comment]
Upgrading from swig 3.0 to swig 4.0 does seem to have resolved the `scm_listify` issue.

**Comment by pemsley** [comment]
OK, interesting. I can close this now?

**Comment by jcbollinger** [comment]
As far as I am concerned, yes, you can close it.
