### ISSUE TITLE
build issues -- Python and RDKit + _ctypes module. Then Unable to create a GL context in Coot

### ISSUE THREAD

**Issue by MTclement1** [pemsley/coot#224]
Hi, 

I fought all day to make it work but I managed to compile coot from source using the build it script on Ubuntu 24.04.

Here are my findings to help people do it if you encounter the same issues. It also has used/is a follow up of #142 and #126 (all line indication are based on the master build-it-3-3 file as of writing).

I implemented changes from the #126 comment https://github.com/pemsley/coot/issues/126#issuecomment-2396910036 : 

- Line 1194: Changed libncurses5-dev to libncurses-dev
- Line 3151: Changed the test to ubuntu to that modern cairo is build using ninja and meson
- Line 4320: Changed pygobject_version to 3.44.2 as it is the latest version on the $extra_places website.

Also had error with ninja, meson, rdkit and readline.

## Readline

Basically readline failed to properly link silently ==> python couldn't install readline module ==> _ctypes module was not install due to this ==> the _ctypes module check failed to pass and program exited.

So i fixed the readline issue by applying the same patch from arch=debian to my case (arch=ubuntu). This compiled readline with libcurse which thus created 0 error during python install and thus _ctypes was working.

## Meson

But then meson wouldn't install: no setuptools
Solution was to add it the part with pip3 install.

## Ninja

Ninja wouldn't install: no pipes module
Python 13.3 removed pipes so last ninja version is needed. I tested and it worked with 1.12.2

## RDKIT

Then RDKIT would for some obscur reason always take my anaconda python over the python set in -DPYTHON_EXECUTABLE, the env variable PYTHON_EXECUTABLE and the fact that the autoinstall python had priority in the path too !
Only fix I found was to use `conda deactivate` before running the script. 

## Pygobject

The test for presence of pygob in /usr/include does not have the ls before it and therefore is always true and pygobject is only installed via the pip3 way latter. 
But this prevents compilation of coot because the pkg-config doesn't see the pip3 installed pygobject. Maybe its an error on my end but my solution was to compile pygobject as in the script (by correcting the test the skip_build variable is thus false).

During pygobject install, the extracted folder has no uppercase letters, but the cd command uses capital letter and thus fails. I changed the line 4353 to:
cd pygobject-$pygobject_version || { echo "cd to pygobject failed"; exit 127; }  from cd PyGObject-$pygobject_version 

## COOT

The coot still fails to build due to an error 

> In file included from ../../coot/utils/next-file-version.cc:6:
> ../../coot/utils/next-file-version.hh:4:8: error: ‘optional’ in namespace ‘std’ does not name a template type
>     4 |   std::optional<int>
>       |        ^~~~~~~~
> ../../coot/utils/next-file-version.hh:1:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
>   +++ |+#include <optional>
>     1 | 
> ../../coot/utils/next-file-version.cc:10:6: error: ‘optional’ in namespace ‘std’ does not name a template type
>    10 | std::optional<int>
>       |      ^~~~~~~~
> ../../coot/utils/next-file-version.cc:7:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
>     6 | #include "next-file-version.hh"
>   +++ |+#include <optional>
>     7 | 
> ../../coot/utils/next-file-version.cc: In function ‘int coot::next_file_version(const std::string&, const std::string&, const std::string&)’:
> ../../coot/utils/next-file-version.cc:58:29: error: ‘parse_version’ was not declared in this scope; did you mean ‘max_version’?
>    58 |          if (auto version = parse_version(filename, stub, extension, directory)) {
>       |                             ^~~~~~~~~~~~~
>       |                             max_version
> make[1]: *** [Makefile:685: next-file-version.lo] Error 1

This is out of my scope as I don't know anything about C/C++ but I followed the error suggestion and changed `+#include <optional>` which reduced the error to: 
../../coot/utils/next-file-version.cc: In function ‘std::optional<int> coot::parse_version(const std::string&, const std::string&, const std::string&, const std::string&)’:
../../coot/utils/next-file-version.cc:27:43: error: ‘all_of’ is not a member of ‘std’
   27 |          if (!version_str.empty() && std::all_of(version_str.begin(), version_str.end(), ::isdigit)) {
      |                                           ^~~~~~
make[1]: *** [Makefile:685: next-file-version.lo] Error 1

That i was able to correct by adding `+#include <algorithm>`

With all that I was able to build coot from source.

## Unable to create a GL context

The program start and nothing of interest seems to be in the log. Yet I get this error.
This one I don't know, I hope someone can help me figure how to deal with the last step. It was built with GTK 4.14.2

==> The answer was also in #126 a little futher:
GDK_DEBUG=gl-glx ./coot does the trick.

## Conclusion

I think some changes can be implemented in the build-it-file, at least some typo around the pygobject stuff and maybe some changes to the arch test. I do not know how to propose those change directly throught github, sorry @pemsley.

**Comment by pemsley** [comment]
> I fought all day to make it work
Sigh. Yes. I find the build script by far the most time-consuming and frustrating part of the whole Coot thing.

 > GDK_DEBUG=gl-glx ./coot does the trick.
This doesn't work for me, for the record.
Yes, including `<optional>` should help/be the solution.
I have done that now 5b6d55587c6bcacda0973e346b4dc5026bf3f9f4
Yes, including `<algorithm>` in `next-file-version.cc` should help/be the solution.
I have done that now 993e293d96eda5870ad6571b54c568d65b3257e7

> The test for presence of pygob in /usr/include does not have the ls before it

Opps! Yes. Fixed: 215f85c719508bed88440b1e6724b2515fa24537

> Then RDKIT would for some obscur reason always take my anaconda python over the python set in -DPYTHON_EXECUTABLE
I see similar sometimes. I find CMake enfuriating.

Note that you can try `--opengl-es` on the command line as an alternative (fallback) graphics environment.

**Comment by MTclement1** [comment]
Thanks you :)

**Comment by eunos-1128** [comment]
The `GDK_DEBUG=gl-glx coot` trick does not work well with gtk 4.16 and above.
Instead, `GDK_DEBUG=gl-prefer-gl coot` may be used to create a GL context .

This has been tested with the current version of the Flatpak coot and adopted.

More details about this can be found in the comments below.
https://github.com/pemsley/coot/issues/161#issuecomment-2570148078

**Comment by eunos-1128** [comment]
The current Flatpak Coot uses GNOME 48 as its base Platform (runtime) and SDK, which should include the following packages mentioned in this issue

- Readline (Platform?) 
- Meson (SDK) 
- Ninja (SDK) 
- Pygobject (Platform) 

These Flatpak can  be installed and check the versions of these packages in the sandbox environment.

``shell 
flatpak install flathub org.gnome.Platform//48 
flatpak install flathub org.gnome.Sdk//48 

# Enter within the Sandbox environment 
flatpak run --command=sh org. Platform//48 
flatpak run --command=sh org.gnome.Platform//48 

# Check package version 
ninja --version 
```

**Comment by pemsley** [comment]
> `GDK_DEBUG=gl-prefer-gl`

Ah! Yes! Great! That works.

**Comment by eunos-1128** [comment]
@pemsley 

I wasn't aware of that in the documentation either...

I tracked it down by following the source code.
